### ISSUE TITLE
What is JBuilder, and where do we get it?

### ISSUE THREAD

**Issue by gregr** [jfeser/L2#2]
Hi,

Your build depends on JBuilder, but doesn't otherwise tell us anything about it.  When I search for JBuilder, I see several different JBuilder projects available.

Which one is the right one?  Can you at least provide a link in the README?  Thanks.

**Comment by jfeser** [comment]
This is the right one (now called Dune): https://github.com/ocaml/dune.

Install it with `opam install jbuilder`.
